version: '3'

### how to run:
### docker-compose build --no-cache 
### docker-compose up --remove-orphans

services:

  postgres_db:
    image: postgres:11.1
    environment:   # Set up postgres database name and password
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    ports:    
      - 5433:5432
    networks:
      - app-tier
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  python_app:
    build:
      context: ./code
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    networks:
      - app-tier
    ports:   
      - 8050:8050


networks:
  app-tier:
    driver: bridge

