CREATE TABLE if not exists dashboard (
date TIMESTAMP WITHOUT TIME ZONE,
high DOUBLE PRECISION,
volume BIGINT,
open DOUBLE PRECISION,
low DOUBLE PRECISION,
close DOUBLE PRECISION,
ticker TEXT,
id SERIAL PRIMARY KEY);
